apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-mtu-configmap
  namespace: {{ .Release.Namespace }}
  labels: {{ include "labels" . | nindent 4 }}
data:
  mtu-customizer.sh: |
    #!/bin/sh

    for interface_path in $(find /sys/class/net  -type l -print)
    do
        interface=$(basename ${interface_path})

        if ls -l ${interface_path} | grep -q virtual
        then
            echo skipping virtual interface: ${interface}
            continue
        fi

        echo changing mtu of non-virtual interface: ${interface}
        ip link set dev ${interface} mtu 1460
    done
