apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "name" . }}-logging-config
  namespace: garden
  labels:
    extensions.gardener.cloud/configuration: logging
data:
  filter-kubernetes.conf: |
    [FILTER]
        Name                parser
        Match               kubernetes.cloud-controller-manager*aws-cloud-controller-manager*
        Key_Name            log
        Parser              kubeapiserverParser
        Reserve_Data        True

    [FILTER]
        Name                parser
        Match               kubernetes.machine-controller-manager*aws-machine-controller-manager*
        Key_Name            log
        Parser              kubeapiserverParser
        Reserve_Data        True
{{ if eq .Values.gardener.seed.provider "aws" }}
    [FILTER]
        Name                parser
        Match               kubernetes.*lb-readvertiser*aws-lb-readvertiser*
        Key_Name            log
        Parser              lbReadvertiserParser
        Reserve_Data        True
{{- end}}
    [FILTER]
        Name record_modifier
        Match *aws-cloud-controller-manager*
        Record type user
{{ if eq .Values.gardener.seed.provider "aws" }}
  parsers.conf: |
    [PARSER]
        Name        lbReadvertiserParser
        Format      regex
        Regex       ^time="(?<time>\d{4}-\d{2}-\d{2}T[^"]*)"\s+level=(?<severity>\w+)\smsg="(?<log>.*)"
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S%Z
{{ end}}