apiVersion: v1
kind: Service
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    networking.resources.gardener.cloud/from-world-to-ports: '[{"protocol":"TCP","port":{{ .Values.webhookConfig.serverPort }}}]'
    networking.resources.gardener.cloud/from-all-seed-scrape-targets-allowed-ports: '[{"port":{{ .Values.metricsPort }},"protocol":"TCP"}]'
    networking.resources.gardener.cloud/from-all-webhook-targets-allowed-ports: '[{"protocol":"TCP","port":{{ .Values.webhookConfig.serverPort }}}]'
    networking.resources.gardener.cloud/namespace-selectors: '[{"matchLabels":{"kubernetes.io/metadata.name":"garden"}},{"matchLabels":{"gardener.cloud/role":"shoot"}}]'
    networking.resources.gardener.cloud/pod-label-selector-namespace-alias: extensions
    {{- if .Values.ignoreResources }}
    resources.gardener.cloud/ignore: "true"
    {{- end }}
    {{- if .Values.gardener.seed.spec.settings.topologyAwareRouting.enabled }}
    {{- if semverCompare ">= 1.27-0" .Capabilities.KubeVersion.Version }}
    service.kubernetes.io/topology-mode: "auto"
    {{- else }}
    service.kubernetes.io/topology-aware-hints: "auto"
    {{- end }}
    {{- end }}
    # TODO: This label approach is deprecated and no longer needed in the future. Remove them as soon as gardener/gardener@v1.75 has been released.
    networking.resources.gardener.cloud/from-policy-pod-label-selector: all-seed-scrape-targets
    networking.resources.gardener.cloud/from-policy-allowed-ports: '[{"port":{{ .Values.metricsPort }},"protocol":"TCP"}]'
  labels:
{{ include "labels" . | indent 4 }}
    {{- if .Values.gardener.seed.spec.settings.topologyAwareRouting.enabled }}
    endpoint-slice-hints.resources.gardener.cloud/consider: "true"
    {{- end }}
spec:
  type: ClusterIP
  selector:
{{ include "labels" . | indent 6 }}
  ports:
  - port: {{ .Values.webhookConfig.servicePort }}
    protocol: TCP
    targetPort: {{ .Values.webhookConfig.serverPort }}
