apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: extensions.gardener.cloud:provider-aws:aws-custom-route-controller
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: aws-custom-route-controller
    namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extensions.gardener.cloud:provider-aws:aws-custom-route-controller
