machineClasses:
- name: class-1
# labels:
#   foo: bar
  ami: ami-123456
  region: eu-west-1
  machineType: m4.xlarge
  iamInstanceProfile: nodes
  keyName: my-ssh-key
  networkInterfaces:
  - subnetID: subnet-acbd1234
    securityGroupIDs:
    - sg-xyz12345
  tags:
    Name: shoot-crazy-botany
    kubernetes.io/cluster/shoot-crazy-botany: "1"
    kubernetes.io/role/node: "1"
  secret:
    cloudConfig: base64(abc)
  credentialsSecretRef:
    name: cloudprovider
    namespace: shoot-namespace
  # labels:
  #   foo: bar
  blockDevices:
  - ebs:
      volumeSize: 50
      volumeType: gp2
    # iops: 100
    # snapshotID: snap-12345
