images:
  machine-controller-manager: image-repository:image-tag
  machine-controller-manager-provider-aws: image-repository:image-tag

replicas: 1

podAnnotations: {}

podLabels: {}

providerName: provider-foo

namespace:
  uid: uuid-of-namespace

metricsPort: 10258
metricsPortAWS: 10259

machineDrainTimeoutAWS: 2h

vpa:
  enabled: true
  updatePolicy:
    updateMode: "Auto"
