global:
  genericTokenKubeconfigSecretName: generic-token-kubeconfig

cloud-controller-manager:
  enabled: true
csi-driver-controller:
  enabled: true
aws-custom-route-controller:
  enabled: false
aws-load-balancer-controller:
  enabled: false
