{{- if .Values.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: aws-custom-route-controller-vpa
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: aws-custom-route-controller
  updatePolicy:
    updateMode: {{ .Values.vpa.updatePolicy.updateMode | quote }}
  resourcePolicy:
    containerPolicies:
    - containerName: aws-custom-route-controller
      minAllowed:
        cpu: {{ .Values.resources.requests.cpu }}
        memory: {{ .Values.resources.requests.memory }}
      controlledValues: RequestsOnly
{{- end }}
