apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aws-load-balancer-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.deploymentAnnotations }}
  annotations:
  {{- toYaml .Values.deploymentAnnotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "aws-load-balancer-controller.labels" . | nindent 4 }}
    # start provider-aws-specific
    gardener.cloud/role: controlplane
    high-availability-config.resources.gardener.cloud/type: controller
    # end provider-aws-specific
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "aws-load-balancer-controller.selectorLabels" . | nindent 6 }}
  {{- with .Values.updateStrategy }}
  strategy:
    {{ toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "aws-load-balancer-controller.selectorLabels" . | nindent 8 }}
        {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.podAnnotations }}
        {{- toYaml .Values.podAnnotations | nindent 8 }}
        {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: {{ template "aws-load-balancer-controller.webhookCertSecret" . }}
      # start provider-aws-specific
      - name: kubeconfig
        projected:
          defaultMode: 420
          sources:
            - secret:
                items:
                  - key: kubeconfig
                    path: kubeconfig
                name: {{ .Values.global.genericTokenKubeconfigSecretName }}
                optional: false
            - secret:
                items:
                  - key: token
                    path: token
                name: shoot-access-aws-load-balancer-controller
                optional: false
      - name: cloudprovider
        projected:
          defaultMode: 420
          sources:
          - secret:
              items:
              {{- if .Values.useWorkloadIdentity }}
              - key: token
                path: token
              {{- else}}
              # TODO: For some reason the aws sdk does not properly read the role_arn
              # from the shared credentials file.
              # Use the file when we use >= v2.9.0 of aws-load-balancer-controller.
              - key: credentialsFile
                path: credentialsFile
              {{- end }}
              name: cloudprovider
              optional: false
      # end provider-aws-specific
      {{- with .Values.extraVolumes }}
      {{ toYaml . | nindent 6 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.hostNetwork }}
      hostNetwork: true
      {{- end }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        args:
        - --cluster-name={{ required "Chart cannot be installed without a valid clusterName!" .Values.clusterName }}
        {{- if .Values.ingressClass }}
        - --ingress-class={{ .Values.ingressClass }}
        {{- end }}
        {{- if .Values.region }}
        - --aws-region={{ .Values.region }}
        {{- end }}
        {{- if .Values.vpcId }}
        - --aws-vpc-id={{ .Values.vpcId }}
        {{- end }}
        {{- if .Values.awsApiEndpoints }}
        - --aws-api-endpoints={{ .Values.awsApiEndpoints }}
        {{- end }}
        {{- if .Values.awsApiThrottle }}
        - --aws-api-throttle={{ join "," .Values.awsApiThrottle }}
        {{- end }}
        {{- if .Values.awsMaxRetries }}
        - --aws-max-retries={{ .Values.awsMaxRetries }}
        {{- end }}
        {{- if kindIs "bool" .Values.enablePodReadinessGateInject }}
        - --enable-pod-readiness-gate-inject={{ .Values.enablePodReadinessGateInject }}
        {{- end }}
        {{- if kindIs "bool" .Values.enableShield }}
        - --enable-shield={{ .Values.enableShield }}
        {{- end }}
        {{- if kindIs "bool" .Values.enableWaf }}
        - --enable-waf={{ .Values.enableWaf }}
        {{- end }}
        {{- if kindIs "bool" .Values.enableWafv2 }}
        - --enable-wafv2={{ .Values.enableWafv2 }}
        {{- end }}
        {{- if .Values.metricsBindAddr }}
        - --metrics-bind-addr={{ .Values.metricsBindAddr }}
        {{- end }}
        {{- if .Values.ingressMaxConcurrentReconciles }}
        - --ingress-max-concurrent-reconciles={{ .Values.ingressMaxConcurrentReconciles }}
        {{- end }}
        {{- if .Values.serviceMaxConcurrentReconciles }}
        - --service-max-concurrent-reconciles={{ .Values.serviceMaxConcurrentReconciles }}
        {{- end }}
        {{- if .Values.targetgroupbindingMaxConcurrentReconciles }}
        - --targetgroupbinding-max-concurrent-reconciles={{ .Values.targetgroupbindingMaxConcurrentReconciles }}
        {{- end }}
        {{- if .Values.targetgroupbindingMaxExponentialBackoffDelay }}
        - --targetgroupbinding-max-exponential-backoff-delay={{ .Values.targetgroupbindingMaxExponentialBackoffDelay }}
        {{- end }}
        {{- if .Values.logLevel }}
        - --log-level={{ .Values.logLevel }}
        {{- end }}
        {{- if .Values.webhookBindPort }}
        - --webhook-bind-port={{ .Values.webhookBindPort }}
        {{- end }}
        {{- if .Values.syncPeriod }}
        - --sync-period={{ .Values.syncPeriod }}
        {{- end }}
        {{- if .Values.watchNamespace }}
        - --watch-namespace={{ .Values.watchNamespace }}
        {{- end }}
        {{- if kindIs "bool" .Values.disableIngressClassAnnotation }}
        - --disable-ingress-class-annotation={{ .Values.disableIngressClassAnnotation }}
        {{- end }}
        {{- if kindIs "bool" .Values.disableIngressGroupNameAnnotation }}
        - --disable-ingress-group-name-annotation={{ .Values.disableIngressGroupNameAnnotation }}
        {{- end }}
        {{- if kindIs "bool" .Values.tolerateNonExistentBackendService }}
        - --tolerate-non-existent-backend-service={{ .Values.tolerateNonExistentBackendService }}
        {{- end }}
        {{- if kindIs "bool" .Values.tolerateNonExistentBackendAction }}
        - --tolerate-non-existent-backend-action={{ .Values.tolerateNonExistentBackendAction }}
        {{- end }}
        {{- if .Values.defaultSSLPolicy }}
        - --default-ssl-policy={{ .Values.defaultSSLPolicy }}
        {{- end }}
        {{- if .Values.externalManagedTags }}
        - --external-managed-tags={{ join "," .Values.externalManagedTags }}
        {{- end }}
        {{- if .Values.defaultTags }}
        - --default-tags={{ include "aws-load-balancer-controller.convertMapToCsv" .Values.defaultTags | trimSuffix "," }}
        {{- end }}
        {{- if kindIs "bool" .Values.enableEndpointSlices }}
        - --enable-endpoint-slices={{ .Values.enableEndpointSlices }}
        {{- end }}
        {{- if kindIs "bool" .Values.enableBackendSecurityGroup }}
        - --enable-backend-security-group={{ .Values.enableBackendSecurityGroup }}
        {{- end }}
        {{- if kindIs "bool" .Values.enableManageBackendSecurityGroupRules }}
        - --enable-manage-backend-security-group-rules={{ .Values.enableManageBackendSecurityGroupRules }}
        {{- end }}
        {{- if .Values.backendSecurityGroup }}
        - --backend-security-group={{ .Values.backendSecurityGroup }}
        {{- end }}
        {{- if kindIs "bool" .Values.disableRestrictedSecurityGroupRules }}
        - --disable-restricted-sg-rules={{ .Values.disableRestrictedSecurityGroupRules }}
        {{- end }}
        {{- if .Values.controllerConfig.featureGates }}
        - --feature-gates={{ include "aws-load-balancer-controller.convertMapToCsv" .Values.controllerConfig.featureGates | trimSuffix "," }}
        {{- end }}
        {{- if ne .Values.defaultTargetType "instance" }}
        - --default-target-type={{ .Values.defaultTargetType }}
        {{- end }}
        {{- if .Values.serviceTargetENISGTags }}
        - --service-target-eni-security-group-tags={{ .Values.serviceTargetENISGTags }}
        {{- end }}
        {{- if .Values.loadBalancerClass }}
        - --load-balancer-class={{ .Values.loadBalancerClass }}
        {{- end }}
        {{- if .Values.vpcTags }}
        - --aws-vpc-tags={{ include "aws-load-balancer-controller.convertMapToCsv" .Values.vpcTags | trimSuffix "," }}
        {{- end }}
        # start provider-aws-specific
        - --kubeconfig=/var/run/secrets/gardener.cloud/shoot/generic-kubeconfig/kubeconfig
        - --leader-election-namespace=kube-system
        # end provider-aws-specific
        env:
        # start provider-aws-specific
        {{- if .Values.useWorkloadIdentity }}
        # TODO: For some reason the aws sdk does not properly read the role_arn
        # from the shared credentials file.
        # Use the file when we use >= v2.9.0 of aws-load-balancer-controller.
        # - name: AWS_SHARED_CREDENTIALS_FILE
        #   value: /var/run/secrets/gardener.cloud/workload-identity/credentialsFile
        - name: AWS_WEB_IDENTITY_TOKEN_FILE
          valueFrom:
            secretKeyRef:
              name: cloudprovider
              key: workloadIdentityTokenFile
        - name: AWS_ROLE_ARN
          valueFrom:
            secretKeyRef:
              name: cloudprovider
              key: roleARN
        {{- else }}
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /srv/cloudprovider/credentialsFile
        {{- end }}
        # end provider-aws-specific
        {{- if .Values.env }}
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{- end }}
        {{- end }}
        command:
        - /controller
        securityContext:
          allowPrivilegeEscalation: false
          {{- toYaml .Values.securityContext | nindent 10 }}
        # start provider-aws-specific
        image: {{ index .Values.images "aws-load-balancer-controller" }}
        # end provider-aws-specific
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
        # start provider-aws-specific
        - name: kubeconfig
          mountPath: /var/run/secrets/gardener.cloud/shoot/generic-kubeconfig
          readOnly: true
        {{- if .Values.useWorkloadIdentity }}
        - name: cloudprovider
          mountPath: /var/run/secrets/gardener.cloud/workload-identity
          readOnly: true
        {{- else }}
        - name: cloudprovider
          mountPath: /srv/cloudprovider
          readOnly: true
        {{- end }}
        # end provider-aws-specific
        {{- with .Values.extraVolumeMounts }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
        ports:
        - name: webhook-server
          containerPort: {{ .Values.webhookBindPort | default 9443 }}
          protocol: TCP
        - name: metrics-server
          containerPort: {{ (split ":" .Values.metricsBindAddr)._1 | default 8080 }}
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- with .Values.livenessProbe }}
        livenessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- else if .Values.configureDefaultAffinity }}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - {{ include "aws-load-balancer-controller.name" . }}
              topologyKey: kubernetes.io/hostname
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
