name: Reusable - Create Branch

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  create-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Git identity # Configure git with a user name and email
        uses: gardener/cc-utils/.github/actions/setup-git-identity@master

      - name: Create new branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Validate input
          if [ -z "${{ inputs.version }}" ]; then
            echo "ERROR: version input is empty"
            exit 1
          fi
          
          VERSION="${{ inputs.version }}"
          # Remove last .X (patch) from the version
          MINOR_VERSION="${VERSION%.*}"
          BRANCH_NAME="release-${MINOR_VERSION}"
          
          # Abort if branch already exists
          if git ls-remote --exit-code --heads origin "${BRANCH_NAME}" >/dev/null 2>&1; then
            echo "Branch ${BRANCH_NAME} already exists on origin. Exiting."
            exit 0
          fi
          git checkout -b "${BRANCH_NAME}"
          
          # Compute next development version
          NEXT_VERSION="${MINOR_VERSION}.1"
          echo "${NEXT_VERSION}-dev" > VERSION
          
          # Generate artifacts
          make generate
          
          # Commit and push changes
          git add --all
          git commit -m "[bot] Prepare next Development Cycle $NEXT_VERSION"
          git push origin $BRANCH_NAME